// IO parameters                                                                                       //## update input and output directory paths
params.outdir = "<path_to_desired_output_directory>/workflow-output/"
workflow_path = "<path_to_dir_with_input_file_and_supplemental_scripts>/workflow"

params.index = """${workflow_path}/nextflow-readfile.csv"""
params.batch_summary_script = """${workflow_path}/parse_busco_batch_summary.py"""
params.sam_processing_script = """${workflow_path}/sam_processing_for_taxa.sh"""

profiles {

    standard {
        process.executor = 'local'
    }

    FNWI {
        
        executor {
            
            name = 'slurm'                                                                                    //##  cluster executor name may need to be updated depending on your cluster
            queueSize = 10
            submitRateLimit = '10/4min'
            exitReadTimeout = '3600 sec'
            killBatchSize = 10
            retry.delay = '5 sec'
        }
 
        process {

            // environment management                                                                            //## update conda env path
            beforeScript = """
            source <path_to_your_conda.sh_file_so_nextflow_can_activate_the_needed_conda_envs>/miniconda3/etc/profile.d/conda.sh                     
            """

            // job management
            executor = 'slurm'                                                                                  //##  cluster executor name may need to be updated depending on your cluster
            scratch = true

            // error management
            errorStrategy = 'ignore'

            withName: whokaryote {         
                cpus = 1
                time = '12.h'
                memory = '48.G'
            }

            withName: concoct {
                cpus = 8
                time = '24.h'
                memory = '24.G'
            }

            withName: busco {
                cpus = 8
                time = '24.h'
                memory = '12.G'
            }

            withName: eukdetect_taxa {
                cpus = 1
                time = '24.h'
                memory = '64.G'
            }

            withName: kaiju_taxa {
                cpus = 1
                time = '12.h'
                memory = '500.G'
            }

        }

    }

}

